### ISSUE TITLE
Sharing other devices infinite loading 

### ISSUE THREAD

**Issue by Tw1x0** [flathub/com.discordapp.DiscordCanary#458]
you cannot share other devices like video capture device or even laptop webcam, this will result in infinite stream loading.

canary 349127 (d49d33d) Host 0.0.528 x64 Build Override: N/A Linux 64-bit (6.11.8-300.fc41.x86_64)

![Screenshot From 2024-11-29 16-05-20](https://github.com/user-attachments/assets/eabd5f58-2577-4dfc-8530-7c51616e4ba8)
![Screenshot From 2024-11-29 16-06-12](https://github.com/user-attachments/assets/b79dbeaa-ea38-44a3-8a46-14cb4b3e6ebc)

**Comment by Nik-mmzd** [comment]
Is the issue reproducible only in the flatpak package? Try running Discord from the tarball, and if the problem persists, report the bug to Discord

P.S. Have you tried granting access to all devices, for example, using FlatSeal or `flatpak --user override com.discordapp.DiscordCanary --device=all`?

**Comment by Tw1x0** [comment]
I had already tried to grant permissions with flatseal and it doesn't work, also I just tried using Discord from the tarball and indeed the error persists.

**Comment by Nik-mmzd** [comment]
>  I just tried using Discord from the tarball and indeed the error persists

You should [report the issue to Discord](https://support.discord.com/hc/en-us/articles/1500006052822-How-to-Report-a-Bug) as this is not an official Discord package and the issue is reproducible with official tarball installation.

Feel free to reopen this issue when the issue will be reproducible only in a Flatpak environment
